### ISSUE TITLE
Major | Check Availability button broken

### ISSUE THREAD

**Issue by Mariakani** [Guestlogix/traveler-ios#214] opened 2019-04-09 13:06 UTC
iOS build 0.3(57)

**Describe The bug**
When user select the date of which to check the availability of the experience items, the check availability button does not seem to be functional and response when click.

**Steps to reproduce**
1. Launch guest app iOS
2. Add flight to the flight lists, say AC862
3. Click on any experience items
4. Navigate to date picker and select a date of which the experience items is available
5. After selecting the date, navigate to **check availability** button at the bottom, and tap on that.
6. Make observation the behavior of the **check availability** button

**Actual result**
The button is momentarily disable once tapped and then able without presenting the next page

**Expect result**
Once check availability button is click, the user should be presented with next page

**Comment by dorothyfu** [comment] 2019-04-09 13:20
Closing, this is caused by #197

**Closed by dorothyfu** 2019-04-09 13:20 UTC
Labels: :bug: bug, MVP, iOS
